# coding: utf-8

"""
    Voucherify API

    Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.

    The version of the OpenAPI document: v2018-08-01
    Contact: support@voucherify.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ExportVoucherTransactionsFields(str, Enum):
    """
    ExportVoucherTransactionsFields
    """

    """
    allowed enum values
    """
    ID = 'id'
    CAMPAIGN_ID = 'campaign_id'
    VOUCHER_ID = 'voucher_id'
    TYPE = 'type'
    SOURCE_ID = 'source_id'
    REASON = 'reason'
    SOURCE = 'source'
    BALANCE = 'balance'
    AMOUNT = 'amount'
    RELATED_TRANSACTION_ID = 'related_transaction_id'
    CREATED_AT = 'created_at'
    DETAILS = 'details'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ExportVoucherTransactionsFields from a JSON string"""
        return cls(json.loads(json_str))


